spring:
  application:
    name: digital-scaffolder-eureka
server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
